blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/h8T2F8WpFN
    about: Ask questions and discuss with other XNum community members 
  - name: Website
    url: https://openscilab.com/
    about: Check out our website for more information
