# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - dev
      - main

env:
  TEST_PYTHON_VERSION: 3.9
  TEST_OS: 'ubuntu-22.04'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macOS-13]
        python-version: [3.7, 3.8, 3.9, 3.10.5, 3.11.0, 3.12.0, 3.13.0]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Test requirements installation
        run: |
          python otherfiles/requirements-splitter.py
          pip install --upgrade --upgrade-strategy=only-if-needed -r test-requirements.txt
      - name: Conflict check
        run: |
          python otherfiles/conflict_check.py
        if: matrix.python-version == env.TEST_PYTHON_VERSION
      - name: Test with pytest 
        run: |
          python -m pytest . --cov=xnum --cov-report=term
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
            fail_ci_if_error: true
            token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.python-version == env.TEST_PYTHON_VERSION && matrix.os == env.TEST_OS
      - name: Vulture, Bandit and Pydocstyle tests
        run: |
          python -m vulture xnum/ otherfiles/ setup.py --min-confidence 65 --exclude=__init__.py --sort-by-size
          python -m bandit -r xnum -s B311,B105
          python -m pydocstyle -v
        if: matrix.python-version == env.TEST_PYTHON_VERSION
      - name: Version check
        run: |
          python otherfiles/version_check.py
        if: matrix.python-version == env.TEST_PYTHON_VERSION
